name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 10 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.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 }}
          USERNAME: ${{ github.AnMnV }}
      - name: Commit & Push
        run: |
          git config user.AnMnV github-actions
          git config user.antonmn1412@gmail.com github-actions@github.com
          git add -A .
          git commit -m "generated"
          git push
